services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
  redis:
    image: redis/redis-stack:latest
    restart: always
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data

volumes:
  db_data:
  redis_data:
